import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {Footer} from '../components/Footer'
import { Main } from '../components/Main'
import { Header } from '../components/Header'
import { useCallback } from 'react'

// const a = 'aiueo'

// const handleClick = (e) => {
//   console.log(e.target)
//   e.preventDefault();
//   alert(a)
// }

export default function Home() {
  const a = 'aiueo'

  const handleClick = useCallback((e) => {
    console.log(e.target)
    e.preventDefault();
    alert(a)
  }, [])
  return (
    <div className={styles.container}>
      <Head>
        <title>Index Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <a
        href='/about'
        onClick={handleClick}>
        ボタン
      </a>

      <Main page={"index"} />

      <Footer/>
    </div>
  )
}
